### DISCUSSION TITLE
How to Delete Default SecurityScheme with OASFilter in java

### DISCUSSION THREAD

**Discussion by Zaccher** [smallrye/smallrye-open-api#1383] [Q&A] [answered]
Hello,
I have a small problem on my OASFilter.
When I go to generate my openapi.yaml file, I get a section (I think by default as I don't enter it directly) called SecurityScheme (in the securitySchemes section) with the following structure:

```
securitySchemes:
    SecurityScheme:
      type: oauth2
      description: Authentication
      flows:
        implicit:
          authorizationUrl: https://...
          tokenUrl: https://....
          refreshUrl: https://....
```
This causes me a small problem, as I would like to fill that section with other information.
How do I remove the SecurityScheme section, which seems to be created by default, from the generation of my file?

Thank you for your help.
