### DISCUSSION TITLE
`@Tag` annotation on Resource producer method

### DISCUSSION THREAD

**Discussion by gquintana** [smallrye/smallrye-open-api#1546] [General]
I would like to place `@Tag` annotations from on a method producing a sub-resource:
```java
@Path("/search")
public class SearchResource {

  @Path("profile1")
  @Tag(name="Profile 1 Resource")
  public SubSearchResource searchProfile1() {
    return new SubSearchResource(profile1Config);
  }

  @Path("profile2")
  @Tag(name="Profile 2 Resource")
  public SubSearchResource searchProfile2() {
    return new SubSearchResource(profile2Config);
  }
```
`SearchResource` is JAX-RS resource class containing several operations.

The generated OpenAPI contracts contains:
```yaml
paths:
  /search/profile1/summary:
    get:
      tags:
      - Sub Search Resource
  /search/profile1/detail:
    get:
      tags:
      - Sub Search Resource
  /search/profile2/summary:
    get:
      tags:
      - Sub Search Resource
  /search/profile2/detail:
    get:
      tags:
      - Sub Search Resource
```
I expect tags to be _Profile 1 Resource_/_Profile 2 Resource_ not _Search Resource_

`@Tag` annotations are OK when placed at Resource class level or at Operation method level (a method returning content).
But they are not OK when placed at Sub-resource producer method level (a method returning a sub-resource).

Is it possible to configure tags using annotations when using sub-resource producer methods?

I am using Quarkus 3.2 with quarkus-smallrye-openapi extension.

**Comment by gquintana** [comment]
Show case https://github.com/smallrye/smallrye-open-api/commit/5eefe45db8fc3b0b72e16cfc01db66e2973f1dbc

**Reply by MikeEdgar** [reply]
@gquintana in the example you linked, is that the expected output or the actual output?

**Reply by gquintana** [reply]
It is the actual output. I would like to have:

```yaml
paths:
  /search/profile1/summary:
    get:
      tags:
      - Profile 1 Resource
  /search/profile1/detail:
    get:
      tags:
      - Profile 1 Resource
  /search/profile2/summary:
    get:
      tags:
      - Profile 2 Resource
  /search/profile2/detail:
    get:
      tags:
      - Profile 2 Resource
 ```
 The `@Tags` at the factory method level could be merge with those at sub resource class level.
 
 See reproducer test case in above above comment.
