### DISCUSSION TITLE
How can I document an Enum value?

### DISCUSSION THREAD

**Discussion by cristalp** [smallrye/smallrye-open-api#2180] [Q&A] [answered]
According to https://swagger.io/docs/specification/v3_0/data-models/enums/ it's possible to add a description to Enum values.

However, annotating them in my code with `@Schema(description = "...")` doesn't do anything.

Is this supported in Smallrye?

**Comment by MikeEdgar** [comment]
I think the description is applied at the parameter level in the example. You can put Markdown in the description so it appears more readable. That's what is shown in the linked doc (in-lined below).

```yaml
parameters:
  - in: query
    name: sort
    schema:
      type: string
      enum: [asc, desc]
    description: >
      Sort order:
       * `asc` - Ascending, from A to Z
       * `desc` - Descending, from Z to A
```
