### ISSUE TITLE
Inherited properties are inlined instead of using allOf

### ISSUE THREAD

**Issue by rbertoncelj** [smallrye/smallrye-open-api#1001]
Properties of superclass are inlined instead of using `allOf` to refer to the superclass.

This was reproduced with smallrye-open-api 2.1.16 on Quarkus.

```java
public static class Greeting extends Message {
    public String name;
}

public static class Message {
    public String text;
}
```

```yaml
components:
  schemas:
    Greeting:
      type: object
      properties:
        text:
          type: string
        name:
          type: string
    Message:
      type: object
      properties:
        text:
          type: string
```

It looks like this has already been fixed in #306 but reappeared again?
