### ISSUE TITLE
`@Schema` in `@Parameter` not supported

### ISSUE THREAD

**Issue by gquintana** [smallrye/smallrye-open-api#1556]
Input:
```java
  @POST
  @Path("foo")
  @Parameter(name = "X-Request-Signature", in = ParameterIn.HEADER, required = true, schema = @Schema(name="string"))
  public Foo getFoo() {
  ```
The Header is handled in a ContainerRequestFilter, hence it absent from method signature
  Output:
  ```yaml
      parameters:
      - name: X-Request-Signature
        in: header
        required: true
        schema: {}
```
`shema` is empty, I would expect `name: string`
