### ISSUE TITLE
Duplicate properties when (not) using bean convention

### ISSUE THREAD

**Issue by rkraneis** [smallrye/smallrye-open-api#1631]
Given the following record (the same issue happens with classes)

```java
	record NotABean(boolean isNotABean, String getReal) {}
```

the following schema is generated:

```yaml
    NotABean:
      type: object
      properties:
        isNotABean:
          type: boolean
        getReal:
          type: string
        notABean:
          type: boolean
        real:
          type: string
```

Which is of course undesirable. As we don't want anything to be interpreted according to the "Java Beans Convention": Can this be configured somehow?
