### ISSUE TITLE
Merging enum schema with "YES" / "NO" literals gives "true" / "false" in resulting yaml.

### ISSUE THREAD

**Issue by soberich** [smallrye/smallrye-open-api#168]
Hi,

Leaving openapi.yaml in `wepapp/META-INF/` with 
```yaml
...
components:
  schemas:
    "Insurance":
      title: "InsuranceStatus"
      type:  string
      enum:
        - YES
        - NO
        - NEVER
...
```

gives
```yaml
...
components:
  schemas:
    Insurance:
      title: InsuranceStatus
      enum:
        - true
        - false
        - NEVER
      type:  string
...
```
THOUGH in `examples` are not affected and preserve "YES" / "NO" values for schemas' properties.
