### ISSUE TITLE
boolean default value

### ISSUE THREAD

**Issue by Postremus** [smallrye/smallrye-open-api#2165]
I have a query param in my resource of type boolean, primitive. If the client does not specify it, it is set to false (since default of primitive boolean).
Can this please also be reflected in openapi?

```
    @QueryParam("deleted")
    public boolean deleted;
```

Instead of:

![Image](https://github.com/user-attachments/assets/b0e854d1-79ea-43c7-bd12-7725f535c922)

```
- 
        name: deleted
        in: query
        schema:
          type: boolean
```

I want:

![Image](https://github.com/user-attachments/assets/99dffdcb-1ebc-4187-a47b-6df6cfc97c49)

```
- in: query
        schema:
          type: boolean
          default: false
```

Is this something you would add as default in this project, or should I annotate all my booleans with @DefaultValue("false")?
