### ISSUE TITLE
TIME_LOCAL_FORMAT example breaks json/yaml parser

### ISSUE THREAD

**Issue by jskov** [smallrye/smallrye-open-api#2193]
The example included with [TIME_LOCAL_FORMAT](https://github.com/smallrye/smallrye-open-api/blob/08831ba6bf7b159e6917165d467ca9cc9b630764/core/src/main/java/io/smallrye/openapi/runtime/util/TypeUtil.java#L107) gets rendered as:

```yaml
                  type: string
                  format: local-time
                  examples:
                  - 13:45:30.123456789
                  externalDocs:
                    description: As defined by 'partial-time' in RFC3339
                    url: https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6
```

Jackson does not like the example. It dies with: `Malformed numeric value '13:45:30.123456789'`

Quoting it helps.

FWIW the example with timezone (+2:00) works. But may be worth quoting as well?!
