### ISSUE TITLE
Upgrading to 4.0.8 from 3.12.0 generates "odd/wrong" yaml

### ISSUE THREAD

**Issue by stalep** [smallrye/smallrye-open-api#2207]
We have an entity: 
https://github.com/Hyperfoil/Horreum/blob/master/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Run.java#L28

Which generates this for the data property
https://github.com/Hyperfoil/Horreum/blob/master/docs/site/content/en/openapi/openapi.yaml#L3977

This is using version; 3.12.0 

When we upgrade to 4.0.8 we see the generated yaml to be:
```
        data:
          type:
          - array
          - string
          description: Run result payload
```
This results in .ts code like:
`data: string<any>;`
Which used to be
`data: string;`

Have we done something wrong in our annotation mapping or is this a regression?
