### ISSUE TITLE
@Parameter with missing name produces duplicate

### ISSUE THREAD

**Issue by jmini** [smallrye/smallrye-open-api#25]
Name is missing in the `@Parameter`:

```java
public Response deleteTask(
@Parameter(
            description = "The id of the task",
            example = "e1cb23d0-6cbe-4a29",
            schema = @Schema(
                    type = SchemaType.STRING))
 @PathParam("taskId")
String taskId) {
    /* .. */
}
```
produces:
```yaml
      parameters:
      - in: path
        description: The id of the task
        schema:
          type: string
        example: e1cb23d0-6cbe-4a29
      - name: taskId
        in: path
        required: true
        schema:
          type: string
```

=> Only one parameter should be generated.

---
An other related problem, name is present:

```java
public Response deleteTask(
@Parameter(
            description = "The id of the task",
            name = "taskId",
            example = "e1cb23d0-6cbe-4a29",
            schema = @Schema(
                    type = SchemaType.STRING))
 @PathParam("taskId")
String taskId) {
    /* .. */
}
```

produces:
```yaml
      parameters:
      - name: taskId
        in: path
        description: The id of the task
        schema:
          type: string
        example: e1cb23d0-6cbe-4a29
```

This is not valid because `required : true` is missing. This is mandatory for path parameter in OpenAPI
