### ISSUE TITLE
Example object in Schema is always of String type

### ISSUE THREAD

**Issue by dmi3coder** [smallrye/smallrye-open-api#300]
I have a very simple User object where I have `id` field of type integer. I added example with specifying the type
``` java
public class User {

    @Schema(type = SchemaType.INTEGER, example = "1000")
    private Integer id;
... constructor, getters, and setters omitted
}
```
This generates a schema with example as a string
```
    User:
      type: object
      properties:
        id:
          format: int32
          type: integer
          example: "1000"
```
Because of this in e.g Swagger UI when I'm prompted to fill in the example I have string type, users can think that it's mandatory to wrap integer into double-quotes.
While debugging I've found that smallrye-open-api reads value from annotation but doesn't do anything with it. The line below `readAttr()` outputs a String object, which should be of type Integer 
https://github.com/smallrye/smallrye-open-api/blob/143d798943cdf3319790eed1e68d327d64728484/core/src/main/java/io/smallrye/openapi/runtime/io/schema/SchemaFactory.java#L196

<img width="1132" alt="Screen Shot 2020-04-17 at 12 15 51" src="https://user-images.githubusercontent.com/12466860/79555360-21e8fe00-80a8-11ea-9e88-3c6ef84104b1.png">
