### ISSUE TITLE
Create API definition from provided dependency in ear

### ISSUE THREAD

**Issue by saschakr** [smallrye/smallrye-open-api#785]
When using a provided dependency in war, the OpenAPI definition is not complete.

Example: 
- example-war 
  - provided dependency on example-jar 
- example-jar
- example-ear
  - bundles both

Expected outcome for /openapi would contains both example schemas

```yaml
components:
  schemas:
    ExampleFromWAR:
      type: object
      properties:
        name:
          type: string
    ExampleFromJAR:
      type: object
      properties:
        name:
          type: string
```

but only the class from the war will be displayed.

A dummy project can be found here:  https://github.com/saschakr/open-api-example
Is there any posibility to fix this?
