### ISSUE TITLE
Enum - "name" is used instead of "toString()" or getter annotated with Jackson @JsonValue

### ISSUE THREAD

**Issue by koalalam** [smallrye/smallrye-open-api#815]
Version: 2.0.26

```java

import com.fasterxml.jackson.annotation.JsonValue;

public enum SampleEnum {
  A("a"),
  B("b"),
  C("c");

  private final String value;

  SampleEnum (String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return this.value;
  }

  @Override
  public String toString() {
    return getValue();
  }
}
```

Expected
```yaml
components:
  schemas:
    SampleEnum:
      enum:
      - a
      - b
      - c
      type: string
```

Actual

```yaml
components:
  schemas:
    SampleEnum:
      enum:
      - A
      - B
      - C
      type: string
```
