### ISSUE TITLE
Multiple classes with same name lead to erroneous openapi.yml and swagger-ui

### ISSUE THREAD

**Issue by ChMThiel** [smallrye/smallrye-open-api#897]
Hello,

I have a problem with multiple classes as OpenApi-Components that share the same name (and live in different packages, of course)
For Example my generated openapi.yml contains following State. It comes form the q/health/ready API's response HealthCheckResponse:

```
components:
  schemas:
    State:
      enum:
      - DOWN
      - UP
      type: string
```

But i have defined a Class State in my project, too. But this is not included in the components of the openapi.yml. I assume there is some name-clash and somehow the other State-Class wins.

I already discused the issue with @phillip-kruger here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/open.20api.3A.20fully.20qualified.20names

Because there is no way (by now) to switch smallrye-open-api to use fully qualified names, we came to following workaround:
I annotated the Class like this:
```
@Schema(description = "State of a Releasable", name = "ReleaseState")
public enum State {
    IN_PROCESS, RELEASED, ARCHIVED
}
```
By doing so, it appeared in the Schema-section of the openapi.yml. 
Nevertheless, if i used the class as a API-parameter, it was not shown propperly:
```
parameters:
      - name: state
        in: query
        schema:
          description: Load TransportOrders in this state
          type: object
```
As you can see the state-parameter has type object and no ref. So i had to add the ref manually like this, and it did the trick:
```
    @QueryParam("state")
    @Schema(description = "Load TransportOrders in this state", ref = "#/components/schemas/ReleaseState")
    private State state;
```

Imho, smallrye should handle class-name-dublettes (e.g. use qualified names in such cases).
And even when Schema-Names are set manually on Class-Level, setting the ref at the parameter should not be necessary - the ref should be generated by smallrye. That might be a bug...

Thanks for your help!
Christian
