### ISSUE TITLE
record with only one property not treated correctly

### ISSUE THREAD

**Issue by nkmohi** [smallrye/smallrye-open-api#937]
A Java record with only one property, such as:

```java
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Schema(description = "Data structure for inputting a responsible delivery team")
public record ResponsibleTeamInput(
    @Schema(description = "Name of the responsible delivery team", example = "team-alpha")
    String responsibleDeliveryTeam
) {
}
```
gets an extra *\<init\>* property:
```yaml
    ResponsibleTeamInput:
      description: Data structure for inputting a responsible delivery team
      type: object
      properties:
        responsibleDeliveryTeam:
          description: Name of the responsible delivery team
          type: string
          example: team-alpha
        <init>:
          description: Name of the responsible delivery team
          type: string
          example: team-alpha
```
If I add another property, the problem disappears.
I am using smallrye-open-api 2.1.15 through Quarkus 2.3.0.
